export const FETCH_BREEDS_REQUEST = 'FETCH_BREEDS_REQUEST'
export const FETCH_BREEDS_SUCCESS = 'FETCH_BREEDS_SUCCESS'
export const FETCH_BREEDS_FAILURE = 'FETCH_BREEDS_FAILURE'
export const SELECT_BREED = 'SELECT_BREED'
